[package]
name = "raytracer"
version = "0.1.0"
authors = ["Ben Clare <ben.clare2@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.23.0"
wgpu = "0.6.0"
wgpu-subscriber = "0.1.0"
futures = "0.3.6"
shaderc = "0.6.2"
